apiVersion: v1
kind: Service
metadata:
  name: bl-api
  namespace: operating
  labels:
    name: bl-api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    name: bl-api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bl-api
  namespace: operating
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: api
        name: bl-api
    spec:
      containers:
      - image: gcr.io/bluelens-11b9b/bl-api:latest
        name: bl-api
        ports:
        - containerPort: 3000
          name: http-server

